In [1]:
import pandas as pd

df = pd.read_csv("CHEMBL-Pt.csv")
display(df)

,Molecule ChEMBL ID,Molecule Name,Compound Key,IC50,Done
0,CHEMBL1743594,"Cis-[Pt(1,3-diaminepropane)2(O-Glutarate)2]",5a,200000.0,True
1,CHEMBL1743593,"Cis-[Pt(1,3-diaminepropane)2] 1,1-cyclobutaned...",1a,200000.0,True
2,CHEMBL1743583,"Cis-[Pt(1,3-diaminebutane)2(OH)2] 1,1-cyclobut...",2a,200000.0,True
3,CHEMBL19739,[{cis-Pt(NH3)2Cl}2(-pzn)]Cl2,1a,91.9,False
4,CHEMBL1794811,"Cis-[Pt(1,3-diaminepropane)2(O-Maleate)2]",4a,200000.0,False
5,CHEMBL2068258,"Cis-[Pt(1,3-diaminebutane) 1,1-cyclobutanedica...",1'b,740.0,False
6,CHEMBL1743591,"Cis-[Pt(1,3-diaminebutane)2(O-Succinate)2]",3b,200000.0,False
7,CHEMBL2068442,"Cis-[Pt(1,3-diaminepropane) 1,1-cyclobutanedic...",1'a,4500.0,True
8,CHEMBL1743584,"Cis-[Pt(1,3-diaminepropane)2(O-Succinate)2]",3a,200000.0,False
9,CHEMBL343632,[Pt(en)BPMAA],[Pt(en)BPMAA],532.0,False
10,CHEMBL1743586,"Cis-[Pt(1,3-diaminepropane)2(OH)2] 1,1-cyclobu...",2b,200000.0,False
11,CHEMBL1743600,"Cis-[Pt(1,3-diaminebutane)2] 1,1-cyclobutanedi...",1b,200000.0,False
12,CHEMBL421775,[Pt(NH3)2BPMAA],[Pt(NH3)2BPMAA],128.0,False
13,CHEMBL4585668,BELZUTIFAN,2,50.0,False

In [2]:
df1 = pd.read_csv("CHEMBL-platinum.csv")
display(df1)

,Molecule ChEMBL ID,Molecule Name,Compound Key,IC50
0,CHEMBL361029,camphorato platinum complex derivative,2b,188.8
1,CHEMBL286548,Platinum complex,1b,58.2
2,CHEMBL2068304,triphenylethylene platinum (II) complex,1Ba,64.0
3,CHEMBL441330,"(2,2':6',2''-terpyridine)platinum (II) complex",4 (NMe(CH2CH2OH)),100.0
4,CHEMBL103847,Trans-Amminedichloro(diethylamine)platinium (II),7,50.0
5,CHEMBL34295,Platinum complex,1d,316.2
6,CHEMBL285449,Platinum complex,1a,60.4
7,CHEMBL6513,Platinum complex,2 (3-F-C5H4N),100.0
8,CHEMBL415294,"(2,2':6',2''-terpyridine)platinum (II) complex",2 (C5H4N),100.0
9,CHEMBL191157,camphorato platinum complex derivative,2a,122.2
10,CHEMBL2068257,platinum complex,9b,67.4
11,CHEMBL2068529,platinum complex,6d,52.1
12,CHEMBL177971,Cis-Platinum (II) Conjugate,7,126.8
13,CHEMBL2146200,Platinum complex,Cipa,65.0
14,CHEMBL175535,Cis-Platinum (II) Conjugate,8,952.2
15,CHEMBL1794812,Platinum complex,4b,200000.0
16,CHEMBL38376,Platinum complex,1c,109.8
17,CHEMBL440148,3-(7a-Chloro-7-diisopropylamino-hexahydro-6-ox...,22,125.0
18,CHEMBL2068444,triphenylethylene platinum (II) complex,1Bb,56.0
19,CHEMBL2068294,triphenylethylene platinum (II) complex,1Cc,67.0
20,CHEMBL177920,Cis-Platinum (II) Conjugate,6,66.0
21,CHEMBL34701,Platinum complex,1f,119.0
22,CHEMBL2068253,platinum complex,9a,92.2
23,CHEMBL2068256,Platinum complex,6b,123.8
24,CHEMBL175844,Cis-Platinum (II) Conjugate,9,135.9
25,CHEMBL33911,Platinum complex,1g,85.2
26,CHEMBL2068520,platinum complex,6a,54.3
27,CHEMBL1743585,Platinum complex,5b,200000.0
28,CHEMBL308922,3-Acetamido-6-Aminocoumarin Platinum (II) Complex,3c,130.2
29,CHEMBL2068254,Platinum complex,6c,55.5
30,CHEMBL308885,7-Amino-4-Methyl-Coumarin Platinum (II) Complex,3e,163.3